/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppAnalyticsRouteImport } from './routes/app/analytics'
import { Route as AppAppointmentsRouteImport } from './routes/app/appointments'
import { Route as AppInboxRouteImport } from './routes/app/inbox'
import { Route as AppIntelRouteImport } from './routes/app/intel'
import { Route as AppInventoryRouteImport } from './routes/app/inventory'
import { Route as AppPipelineRouteImport } from './routes/app/pipeline'
import { Route as AppSequencesRouteImport } from './routes/app/sequences'
import { Route as AppTeamRouteImport } from './routes/app/team'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAppointmentsRoute = AppAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppIntelRoute = AppIntelRouteImport.update({
  id: '/intel',
  path: '/intel',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppPipelineRoute = AppPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AppRoute,
} as any)
const AppSequencesRoute = AppSequencesRouteImport.update({
  id: '/sequences',
  path: '/sequences',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/appointments': typeof AppAppointmentsRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/intel': typeof AppIntelRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/pipeline': typeof AppPipelineRoute
  '/app/sequences': typeof AppSequencesRoute
  '/app/team': typeof AppTeamRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/appointments': typeof AppAppointmentsRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/intel': typeof AppIntelRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/pipeline': typeof AppPipelineRoute
  '/app/sequences': typeof AppSequencesRoute
  '/app/team': typeof AppTeamRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/appointments': typeof AppAppointmentsRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/intel': typeof AppIntelRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/pipeline': typeof AppPipelineRoute
  '/app/sequences': typeof AppSequencesRoute
  '/app/team': typeof AppTeamRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/analytics'
    | '/app/appointments'
    | '/app/inbox'
    | '/app/intel'
    | '/app/inventory'
    | '/app/pipeline'
    | '/app/sequences'
    | '/app/team'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/analytics'
    | '/app/appointments'
    | '/app/inbox'
    | '/app/intel'
    | '/app/inventory'
    | '/app/pipeline'
    | '/app/sequences'
    | '/app/team'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/analytics'
    | '/app/appointments'
    | '/app/inbox'
    | '/app/intel'
    | '/app/inventory'
    | '/app/pipeline'
    | '/app/sequences'
    | '/app/team'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/appointments': {
      id: '/app/appointments'
      path: '/appointments'
      fullPath: '/app/appointments'
      preLoaderRoute: typeof AppAppointmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inbox': {
      id: '/app/inbox'
      path: '/inbox'
      fullPath: '/app/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/intel': {
      id: '/app/intel'
      path: '/intel'
      fullPath: '/app/intel'
      preLoaderRoute: typeof AppIntelRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inventory': {
      id: '/app/inventory'
      path: '/inventory'
      fullPath: '/app/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pipeline': {
      id: '/app/pipeline'
      path: '/pipeline'
      fullPath: '/app/pipeline'
      preLoaderRoute: typeof AppPipelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sequences': {
      id: '/app/sequences'
      path: '/sequences'
      fullPath: '/app/sequences'
      preLoaderRoute: typeof AppSequencesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/team': {
      id: '/app/team'
      path: '/team'
      fullPath: '/app/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAppointmentsRoute: typeof AppAppointmentsRoute
  AppInboxRoute: typeof AppInboxRoute
  AppIntelRoute: typeof AppIntelRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppPipelineRoute: typeof AppPipelineRoute
  AppSequencesRoute: typeof AppSequencesRoute
  AppTeamRoute: typeof AppTeamRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAppointmentsRoute: AppAppointmentsRoute,
  AppInboxRoute: AppInboxRoute,
  AppIntelRoute: AppIntelRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppPipelineRoute: AppPipelineRoute,
  AppSequencesRoute: AppSequencesRoute,
  AppTeamRoute: AppTeamRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
